name: CI

on:

  push:
    branches:
      - main
    paths:
      - include/**
      - Makefile
      - src/**
  workflow_dispatch:

jobs:

  build-and-run:
    name: Build project and run default case
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y update && \
          sudo apt-get -y install make
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          ref: ${{ github.ref_name }}
      - name: Compile
        run: |
          make ARG_CFLAG="-fopenmp -flto" all
      - name: Run case
        run: |
          make output
          OMP_NUM_THREADS=2 ./a.out

  perform-unit-tests:
    name: Perform unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cases: ["dft/dct", "dft/rdft", "tdm", "transpose"]
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y update && \
          sudo apt-get -y install make
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          ref: ${{ github.ref_name }}
      - name: Compile and run cases
        run: |
          cd src/${{ matrix.cases }}
          make ARG_CFLAG="-fopenmp -flto" all
          OMP_NUM_THREADS=2 ./a.out

